"""Playlist, artist, and keyword to genre mappings."""

# Playlist name → genre
PLAYLIST_GENRE = {
    "2000s": "Pop",
    "2000s remixes": "Pop Remix",
    "Brasil": "Brazilian",
    "Cocktail": "Lounge",
    "Comercial": "Pop",
    "Cotillon": "Party",
    "Cuarteto": "Cuarteto",
    "Cumbbia": "Cumbia",
    "Cumbias viejas": "Cumbia",
    "Dance:Disco": "Disco",
    "Disco": "Disco",
    "España": "Pop Español",
    "Internacional": "Pop",
    "Latino": "Latin Pop",
    "Lentos": "Balada",
    "Oldies": "Oldies",
    "oldies ": "Oldies",
    "Regaeton": "Reggaeton",
    "Reggaeton": "Reggaeton",
    "Remixes Latinos": "Latin Remix",
    "Rock Argentino": "Rock Nacional",
    "Spotify - BODAS ESPAÑOLAS": "Pop Español",
    "Spotify - Casamiento Uruguay": "Latin Pop",
    "Spotify - German Wedding Songs": "Pop",
    "bilables viejos latinos": "Latin Pop",
    "boda aggus & hannnah - guidomix": "Party",
    "pop latino": "Latin Pop",
}

# Artist name (lowercase, partial match) → genre
ARTIST_GENRE = {
    "rodrigo": "Cuarteto",
    "la mona jimenez": "Cuarteto",
    "ulises bueno": "Cuarteto",
    "daddy yankee": "Reggaeton",
    "don omar": "Reggaeton",
    "bad bunny": "Reggaeton",
    "j balvin": "Reggaeton",
    "ozuna": "Reggaeton",
    "maluma": "Reggaeton",
    "nicky jam": "Reggaeton",
    "wisin": "Reggaeton",
    "anuel": "Reggaeton",
    "rauw alejandro": "Reggaeton",
    "karol g": "Reggaeton",
    "farruko": "Reggaeton",
    "plan b": "Reggaeton",
    "gilda": "Cumbia",
    "los palmeras": "Cumbia",
    "los auténticos decadentes": "Rock Nacional",
    "los piojos": "Rock Nacional",
    "la renga": "Rock Nacional",
    "soda stereo": "Rock Nacional",
    "fito paez": "Rock Nacional",
    "charly garcia": "Rock Nacional",
    "michael jackson": "Pop",
    "madonna": "Pop",
    "cyndi lauper": "Pop",
    "beyoncé": "Pop",
    "rihanna": "Pop",
    "black eyed peas": "Pop",
    "david guetta": "EDM",
    "tiesto": "EDM",
    "shakira": "Latin Pop",
    "ricky martin": "Latin Pop",
    "pitbull": "Latin Pop",
    "marc anthony": "Salsa",
    "sean paul": "Dancehall",
    "bob sinclar": "Disco",
}

# Title keyword (lowercase) → genre
TITLE_KEYWORDS = {
    "reggaeton": "Reggaeton",
    "perreo": "Reggaeton",
    "dembow": "Reggaeton",
    "cumbia": "Cumbia",
    "cuarteto": "Cuarteto",
    "salsa": "Salsa",
    "bachata": "Bachata",
    "merengue": "Merengue",
    "disco": "Disco",
    "house": "House",
    "techno": "Techno",
    "guaracha": "Guaracha",
    "tribal": "Tribal",
    "afrohouse": "Afro House",
    "afro house": "Afro House",
}
